version: '3.9'
services:
    weblog_application:
        build:
            args:
                user: idanieldrew
                uid: 1000
            context: docker/
            dockerfile: Dockerfile
        image: medium
        container_name: weblog_application
        restart: unless-stopped
        depends_on:
            - redact_rabbit
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        #            - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - weblog-network

    medium_webserver:
        image: nginx:1.21.3
        container_name: medium-web-server
        restart: always
        tty: true
        ports:
            - "80:80"
        #      - "443:443"
        volumes:
            - .:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - weblog_application
        networks:
            - weblog-network

    medium_database:
        image: postgres:14.2-alpine
        container_name: mediumdb
        restart: unless-stopped
        tty: true
        depends_on:
            - weblog_application
        ports:
            - "54320:5432"
        environment:
            POSTGRES_DB: "medium"
            POSTGRES_USER: "dani"
            POSTGRES_PASSWORD: "password"
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - weblog-network

    medium_redis:
        image: redis:7-alpine
        container_name: medium_redis
        depends_on:
            - weblog_application
        ports:
            - "6379:6379"
        volumes:
            - cache-data:/data
            - ./docker/redis.conf:/redis.conf
        networks:
            - weblog-network

    medium_elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        container_name: medium_elasticsearch
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - elastic:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - 9300:9300
        networks:
            - weblog-network

    redact_rabbit:
        image: rabbitmq:3.11.3-management
        container_name: redact_rabbit
        tty: true
        environment:
            DEFAULT_VHOST: /
            DEFAULT_USER: guest
            DEFAULT_PASS: guest
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
            - rabbitmq-data2:/var/log/rabbitmq
        networks:
            - weblog-network

    medium_kibana:
        image: docker.elastic.co/kibana/kibana:7.4.0
        container_name: mediumKibana
        environment:
            - ELASTICSEARCH_HOSTS=http://medium_elasticsearch:9200
        depends_on:
            - medium_elasticsearch
        ports:
            - 5601:5601
        networks:
            - weblog-network


    testlink:
        shm_size: 1g
        image: bitnami/testlink:latest
        container_name: medium_testlink
        depends_on:
            - medium_database
        ports:
            - "8088:8080"
            - "8443:8443"
        user: root
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - TESTLINK_USERNAME=dani
            - TESTLINK_PASSWORD=password
            - TESTLINK_DATABASE_USER=daniel
            - TESTLINK_DATABASE_PASSWORD=password
            - TESTLINK_DATABASE_NAME=bitnami_testlink
            - TESTLINK_DATABASE_HOST=mariadb-testlink
        volumes:
            - testlink_data:/bitnami/testlink
            - testlink_code:/opt/bitnami/testlink

        networks:
            - weblog-network

        privileged: true
networks:
    weblog-network:
        driver: bridge

volumes:
    testlink_data:
    testlink_code:
    dbdata:
        driver: local
    elastic:
        driver: local
    cache-data:
        driver: local
    rabbitmq-data:
        driver: local
    rabbitmq-data2:
        driver: local
