version: '3.9'
services:
    weblog_application:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: medium
        container_name: weblog_application
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        #      - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - weblog-network

    medium_webserver:
        image: nginx:1.21.3
        container_name: medium-web-server
        restart: always
        tty: true
        ports:
            - "80:80"
        #      - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - weblog_application
        networks:
            - weblog-network

    medium_database:
        image: postgres:14.2-alpine
        container_name: mediumdb
        restart: unless-stopped
        tty: true
        depends_on:
            - weblog_application
        ports:
            - "54320:5432"
        environment:
            POSTGRES_DB: "medium"
            POSTGRES_USER: "dani"
            POSTGRES_PASSWORD: "password"
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - weblog-network

    medium_cache:
        image: redis:7-alpine
        container_name: mediumredis
        depends_on:
            - weblog_application
        ports:
            - "6379:6379"
        volumes:
            - cache-data:/data
            - ./docker/redis.conf:/redis.conf
        networks:
            - weblog-network

    medium_elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        container_name: mediumElasticsearch
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - elasti:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - 9300:9300
        networks:
            - weblog-network

    medium_kibana:
        image: docker.elastic.co/kibana/kibana:7.4.0
        container_name: mediumKibana
        environment:
            - ELASTICSEARCH_HOSTS=http://medium_elasticsearch:9200
        depends_on:
            - medium_elasticsearch
        ports:
            - 5601:5601
        networks:
            - weblog-network

networks:
    weblog-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
    elasti:
        driver: local
    cache-data:
        driver: local
