version: '3.9'
services:
    redact_application:
        build:
            args:
                user: idanieldrew
                uid: 1000
            context: docker/
            dockerfile: Dockerfile
        image: redact
        container_name: redact_application
        restart: unless-stopped
        depends_on:
            - redact_rabbitmq
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - redact_network

    redact_webserver:
        image: nginx:1.21.3
        container_name: redact_server
        restart: always
        tty: true
        ports:
            - "80:80"
        #      - "443:443"
        volumes:
            - .:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - redact_application
        networks:
            - redact_network

    redact_database:
        image: postgres:14.2-alpine
        container_name: redact_db
        restart: unless-stopped
        tty: true
        depends_on:
            - redact_application
        ports:
            - "54320:5432"
        environment:
            POSTGRES_DB: "redact"
            POSTGRES_USER: "dani"
            POSTGRES_PASSWORD: "password"
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - redact_network

    redact_cache:
        image: redis:7-alpine
        container_name: redact_redis
        depends_on:
            - redact_application
        ports:
            - "6379:6379"
        volumes:
            - cache-data:/data
            - ./docker/redis.conf:/redis.conf
        networks:
            - redact_network

    redact_elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        container_name: redact_elastic
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - elastic:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - redact_network

    redact_rabbitmq:
        image: rabbitmq:3.11.3-management
        container_name: redact_rabbitmq
        tty: true
        environment:
            DEFAULT_VHOST: /
            DEFAULT_USER: guest
            DEFAULT_PASS: guest
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
            - rabbitmq-data2:/var/log/rabbitmq
        networks:
            - redact_network

    redact_kibana:
        image: docker.elastic.co/kibana/kibana:7.4.0
        container_name: redact_kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://redact_elasticsearch:9200
        depends_on:
            - redact_elasticsearch
        ports:
            - 5601:5601
        networks:
            - redact_network

    redact_filebeat:
        image: docker.elastic.co/beats/filebeat:8.6.2
        container_name: redact_filebeat
        command: filebeat -e -strict.perms=false
        depends_on:
            - redact_elasticsearch
        volumes:
            - ./docker/filebeat/conf.yml:/usr/share/filebeat/filebeat.yml
            - /var/lib/docker:/var/lib/docker:ro
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - redact_network

    minio:
        image: minio/minio
        ports:
            - "9002:9000"
            - "9001:9001"
        volumes:
            - minio_storage:/data
        environment:
            MINIO_ROOT_USER: dani
            MINIO_ROOT_PASSWORD: password
        command: server --console-address ":9001" /data

#    redact_logstash:
#        image: logstash:7.7.0
#        ports:
#            - "9600:9600"
#            - "8089:8089"
#        links:
#            - "redact_elasticsearch"
#        environment:
#            - LOGSTASH_JDBC_URL=jdbc:postgresql://redact_db:5432/postgres
#            - LOGSTASH_JDBC_DRIVER=org.postgresql.Driver
##            - LOGSTASH_JDBC_DRIVER_JAR_LOCATION=docker/logstash/postgresql.jar
#            - LOGSTASH_JDBC_USERNAME=dani
#            - LOGSTASH_JDBC_PASSWORD=password
#            - LOGSTASH_ELASTICSEARCH_HOST=http://redact_elasticsearch:9200
#        volumes:
#            - ./docker/logstash/postgresql.jar:/usr/share/logstash/logstash-core/lib/jars/postgresql.jar
#            - ./docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#        depends_on:
#            - redact_elasticsearch
#        networks:
#            - redact_network

networks:
    redact_network:
        driver: bridge

volumes:
    dbdata:
        driver: local
    elastic:
        driver: local
    cache-data:
        driver: local
    rabbitmq-data:
        driver: local
    rabbitmq-data2:
        driver: local
    logstash:
        driver: local
    filebeat:
        driver: local
    minio_storage:
        driver: local
