filebeat:
  inputs:
    - enabled: true
      json.add_error_key: true
      json.expand_keys: true
      json.keys_under_root: true
      json.overwrite_keys: true
      paths:
        - /var/www/storage/logs/laravel.log
      type: log

output:
  elasticsearch:
    hosts:
      - elasticsearch:9200

logging:
  files:
    rotateeverybytes: 10485760
