filebeat.inputs:
  - type: container
    paths:
      - /var/www/storage/logs/laravel*.log
    enabled: true

output.elasticsearch:
  hosts: ["http://172.19.0.31:9200"]

setup.kibana.host: "172.19.0.41:5601"
