filebeat.inputs:
  - enabled: true
    json.add_error_key: true
    json.expand_keys: true
    json.keys_under_root: true
    json.overwrite_keys: true
    paths:
      - "/usr/share/filebeat/mylog/*.log"
    type: filestream

output.elasticsearch:
  hosts: [ "172.22.0.31:9200" ]

logging:
  files:
    rotateeverybytes: 10485760

setup.kibana.host: "172.22.0.41:5601"
