filebeat.inputs:
  - enabled: true
    json.add_error_key: true
    json.expand_keys: true
    json.keys_under_root: true
    json.overwrite_keys: true
    paths:
      - "/var/www/storage/logs/*.log"
    type: log

output.elasticsearch:
  hosts: [ "172.19.0.4:9200" ]

logging:
  files:
    rotateeverybytes: 10485760

setup.kibana.host: "172.19.0.7:5601"
