<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\Response;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array<int, class-string<Throwable>>
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if ($e instanceof \Symfony\Component\HttpKernel\Exception\NotFoundHttpException) {
            return response()->json([
                'status' => 'fail',
                'message' => 'Not Found',
            ], Response::HTTP_NOT_FOUND, $e->getHeaders());
        } elseif ($e instanceof \Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException) {
            return response()->json([
                'status' => 'fail',
                'message' => $e->getMessage(),
            ], Response::HTTP_METHOD_NOT_ALLOWED, $e->getHeaders());
        } elseif ($e instanceof \Illuminate\Validation\ValidationException) {
            return response()->json([
                'status' => 'fail',
                'message' => $e->getMessage(),
                'errors' => $e->errors(),
            ], Response::HTTP_UNPROCESSABLE_ENTITY);
        } elseif ($e instanceof \Illuminate\Auth\AuthenticationException) {
            return response()->json([
                'status' => 'fail',
                'message' => $e->getMessage(),
            ], Response::HTTP_UNAUTHORIZED);
        } elseif ($e instanceof \Illuminate\Http\Exceptions\ThrottleRequestsException) {
            return response()->json([
                'status' => 'fail',
                'message' => $e->getMessage(),
            ], Response::HTTP_TOO_MANY_REQUESTS, $e->getHeaders());
        } elseif ($e instanceof \Symfony\Component\Routing\Exception\RouteNotFoundException) {
            return response()->json([
                'status' => 'error',
                'message' => $this->isDebugMode() ? $e->getMessage() : 'Internal Server Error',
            ], Response::HTTP_INTERNAL_SERVER_ERROR);
        }

        dd($e);

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

    protected function isDebugMode() {
        return config('app.debug');
    }
}
