global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: redact_prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["redact_postgres-exporter:9187"]
