name: Containers

on: [ push, pull_request ]

jobs:
  laravel-blog-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker-compose up -d
      - name: depend
        run: docker run --rm -v $(pwd):/app composer install
      - name: permission
        run: sudo chown -R $USER:$USER /var/www/html
      - name: show services
        run: docker ps
      - name: key generate
        run: docker-compose exec -T weblog_application php artisan key:generate
      - name: set environment
        run: docker-compose exec -T weblog_application cp .env.example.ci .env
      - name: run tests
        run: docker-compose exec -T weblog_application php artisan test
