name: Containers

on: [ push, pull_request ]

jobs:
  laravel-blog-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker-compose up -d
      - name: show services
        run: docker ps
      - name: remove composer lock
        run: docker-compose exec -T weblog_application rm -rf vendor composer.lock
      - name: composer install
        run: docker-compose exec -T weblog_application composer install
      - name: run tests
        run: docker-compose exec -T weblog_application php artisan test
