name: Docker-ci
on: [ push, pull_request ]
jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Copy environment file
        run: cp .env.example .env
      - name: Run docker
        run: docker-compose up -d
      - name: Check docker
        run: docker ps
      - name: Composer
        run:  docker-compose exec -T redact_application composer install --prefer-dist --no-interaction
      - name: Generate app key
        run: docker-compose exec -T redact_application php artisan key:generate
      - name: Migration
        run: docker-compose exec -T redact_application php artisan migrate:fresh --seed
      - name: Import indexes
        run: docker-compose exec -T redact_application php artisan scout:index posts
      - name: Import db
        run: docker-compose exec -T redact_application php artisan scout:import "Module\Post\Models\Post"
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: docker-compose exec -T redact_application php artisan test
