name: Tests
on: [ push, pull_request ]
jobs:
  laravel-blog:
    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_test
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: elastic
        - uses: getong/elasticsearch-action@v1.2
          with: elasticsearch 
          version: '7.9.1'
          host port: 9200 
          container port: 9200 
          host node port: 9300
          node port: 9300 
          discovery type: 'single-node'
      - name: running tests
        run: |
            sleep 60
            curl -X GET http://elasticsearch:9200/
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Copy environment file
        run: cp .env.example.ci .env
      - name: Generate app key
        run: php artisan key:generate
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: db_test
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: password
        run:
          php artisan test
