name: Tests

on: [ push, pull_request ]

jobs:
  laravel-blog:
    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_test
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Laravel Setup
        run: |
          cp .env.ci .env
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: db_test
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: password
        run:
          php artisan test
